### ISSUE TITLE
Uploading scaler with pickle

### ISSUE THREAD

**Issue by Floppa2003** [newchronik/adjdatatools#2]
Good evening. Thank you for  implementing this interesting scaling method for everyone to use. I am using this scaler in one of my projects and now have to save it in my device. For a usual sklearn scaler I would just use pickle to save it, but when I try to use it with AdjustedScaler I get error EOFError: Ran out of input
<img width="354" alt="image" src="https://user-images.githubusercontent.com/120779629/230981747-63c16c5a-ebf8-4b52-904d-204bded41893.png">
. Is there a possibility to implement saving the scaler via pickle or any place where I can find how to implement it myself? Thanks in advance!

**Comment by newchronik** [comment]
Good evening.
Personally, I prefer the "joblib" library for saving objects to a file.

import joblib

# File saving
joblib.dump(my_object, 'path/to/file')

# File loading
my_loaded_object = joblib.load('path/to/file')



пн, 10 апр. 2023 г. в 22:29, Floppa2003 ***@***.***>:

**Comment by Floppa2003** [comment]
Yeah, thanks, managed to do it with joblib just a couple of minutes ago. Thanks for your quick answer!
